server:
  port: 8888
spring:
  application:
    name: cloud-gateway-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #
        - id: add_request_parameter_route
          # lb 负载均衡
          uri: lb://spring-cloud-producer
          filters:
          ## 可以配置多个过滤器
          # 请求添加上 param=lio 的参数和值。
            - AddRequestParameter=param, lio
          # 自定义过滤器，带前置和后置功能
            - Customer
          predicates:
          ## 可以配置多个匹配规则
            # 根据请求方法匹配
#            - Method=GET
            # 根据路径匹配
            - Path=/customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug